### ISSUE TITLE
有教程吗？

### ISSUE THREAD

**Issue by ZHENGX1N** [aaBaO/JiaGuoMengBox#1]

**Comment by aaBaO** [comment]
也说不上是教程吧，在NGA上有帖子。
[链接](https://bbs.nga.cn/read.php?tid=18884072&_ff=678&page=e#pid372566312Anchor)

**Comment by ZHENGX1N** [comment]
感谢！

鲍向鸿 <notifications@github.com<mailto:notifications@github.com>> 于 2019年10月25日周五 19:15写道：

也说不上是教程吧，在NGA上有帖子。
链接<https://bbs.nga.cn/read.php?tid=18884072&_ff=678&page=e#pid372566312Anchor>
